# Generated by Django 4.0.4 on 2022-07-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bici',
            fields=[
                ('idBici', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la bici')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la bici')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de la bici')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo de la bici')),
                ('color', models.CharField(max_length=50, verbose_name='Color de la bici')),
                ('precio', models.IntegerField(verbose_name='Precio de la bici')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de bicis')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion de la bici')),
                ('imagen', models.ImageField(upload_to='bicis', verbose_name='Imagen de la bici')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la venta')),
                ('fecha', models.DateField(verbose_name='Fecha de la venta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de bicis')),
                ('precio', models.IntegerField(verbose_name='Precio de la venta')),
                ('cliente', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('idBici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterBikes.bici', verbose_name='Id de la bici')),
            ],
        ),
    ]
