# Generated by Django 4.0.4 on 2022-07-08 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bici',
            fields=[
                ('idBici', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la bici')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la bici')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de la bici')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo de la bici')),
                ('color', models.CharField(max_length=50, verbose_name='Color de la bici')),
                ('precio', models.IntegerField(verbose_name='Precio de la bici')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de bicis')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion de la bici')),
                ('imagen', models.ImageField(null=True, upload_to='bicis', verbose_name='Imagen de la bici')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la venta')),
                ('fecha', models.DateField(verbose_name='Fecha de la venta')),
                ('fechaTermino', models.DateField(verbose_name='Fecha de termino de la venta')),
                ('formadepago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=50, verbose_name='Forma de pago')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de bicis')),
                ('precio', models.IntegerField(verbose_name='Precio de la venta')),
                ('cliente', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('idBici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterBikes.bici', verbose_name='Id de la bici')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('idReparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la reparacion')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de la reparacion')),
                ('precio', models.IntegerField(verbose_name='Precio de la reparacion')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado de la reparacion')),
                ('cliente', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('idBici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterBikes.bici', verbose_name='Id de la bici')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la promocion')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de bicis')),
                ('Bicis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterBikes.bici', verbose_name='la bici')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('idDespacho', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del despacho')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del despacho')),
                ('fechaTermino', models.DateField(null=True, verbose_name='Fecha de termino del despacho')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado del despacho')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion del despacho')),
                ('cliente', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterBikes.venta', verbose_name='Id de la venta')),
            ],
        ),
    ]
