# Generated by Django 4.0.4 on 2022-07-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterBikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bici',
            name='imagen',
            field=models.ImageField(null=True, upload_to='bicis', verbose_name='Imagen de la bici'),
        ),
    ]
