# Generated by Django 4.0.4 on 2022-07-08 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterBikes', '0002_alter_bici_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de la venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaTermino',
            field=models.DateField(verbose_name='Fecha de termino de la venta'),
        ),
    ]
